name: Sucker
main: xiaokai.sucker.Sucker
api:
- 1.0.0
version: 1
load: POSTWORLD
website: http://Winfxk.EpicFX.cn
description: 多功能菜单，如传送、命令、提示等功能，并且支持自定义快捷菜单，将一个菜单装进物品内！后期还会加入更多功能哦！
author: Winfxk
commands:
   am:
      description: §9生存锁定插件命令
      permission: Sucker.Command.Main
      usage: §b/§6am §chelp
permissions:
   Sucker.Command.Main:
      description: 菜单工具主命令
      default: true